version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - rm -rf docs/source/generated
      - sphinx-apidoc
        --private
        --module-first
        --force
        --output-dir docs/source/generated
        src/legend_optics
        src/legend_optics/_version.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
